spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/niiuchat
      username: root
      password:
      maximum-pool-size: 20

springdoc:
  api-docs:
    path: /admin/api-docs
  swagger-ui:
    path: /admin/api-docs-ui

logging:
  level:
    root: info
    com.zaxxer.hikari.HikariConfig: debug
